org.gradle.jvmargs=-Xmx3G
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

minecraftVersion=26.1.2
modVersion=26.1.2-1.0.2
currentChangelog=- Fixed grid selector opening when pressing a keybind key and its modifier in quick succession

refinedarchitectVersion=1.6.4
refinedstorageVersion=3.0.5
refinedstorageQuartzArsenalVersion=2.0.4
