org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.configuration-cache=true

modId=create_new_age
modVersion=1.2.0
minecraftVersion=1.20.1

parchmentVersion=2023.09.03

forgeVersion=1.20.1-47.1.99

createVersion=6.0.8-289
ponderVersion=1.0.91

registrateVersion=MC1.20-1.3.3
flywheelVersion=1.0.5

createFabricVersion=6.0.8.0+build.1734-mc1.20.1
registrateFabricVersion=1.3.79-MC1.20.1

eslVersion=1.1.3

jeiVersion=15.20.0.123

recipeViewer=jei

cctVersion=1.117.0

ae2Version=15.4.10

loom.ignoreDependencyLoomVersionValidation=true